#!/usr/bin/env python3
"""
Retrieve Windows EC2 admin passwords and generate Ansible host_vars files.

Usage:
  python3 get-windows-passwords.py < /tmp/ansible-inventory.json

Requires:
  - AWS credentials configured (env vars or IMDS)
  - Private key file path via --private-key or PRIVATE_KEY_FILE env var
  - Ansible inventory JSON on stdin (produced by ansible-inventory --list)
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile


def _unwrap(val):
    """Unwrap __ansible_unsafe dict values and return the inner string."""
    if isinstance(val, dict) and "__ansible_unsafe" in val:
        return val["__ansible_unsafe"]
    return val


def get_instance_id(inventory, ip):
    """Find the EC2 instance ID for a given IP from the inventory _meta."""
    meta = inventory.get("_meta", {}).get("hostvars", {})
    if ip in meta:
        raw = meta[ip].get("ec2_id") or meta[ip].get("instance_id", "")
        return _unwrap(raw) if raw else ""
    return ""


def get_password(instance_id, pem_file):
    """Retrieve and decrypt the Windows admin password for an EC2 instance."""
    try:
        cmd = [
            "aws", "ec2", "get-password-data",
            "--instance-id", instance_id,
            "--priv-launch-key", pem_file,
            "--query", "PasswordData",
            "--output", "text",
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print(f"  WARNING: Failed to get password for {instance_id}: {result.stderr.strip()}", file=sys.stderr)
            return None
        password = result.stdout.strip()
        if password and password != "None" and not password.startswith("None"):
            return password
        return None
    except Exception as e:
        print(f"  WARNING: Error for {instance_id}: {e}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(
        description="Generate Ansible host_vars with Windows admin passwords"
    )
    parser.add_argument(
        "--private-key",
        default=os.environ.get("PRIVATE_KEY_FILE", os.path.expanduser("~/.ssh/deployer_key")),
        help="Path to the private key file for password decryption",
    )
    parser.add_argument(
        "--host-vars-dir",
        default=os.environ.get(
            "ANSIBLE_HOST_VARS_DIR",
            os.path.join(os.path.dirname(__file__), "..", "ansible", "host_vars"),
        ),
        help="Path to the Ansible host_vars directory",
    )
    args = parser.parse_args()

    if not os.path.exists(args.private_key):
        print(f"ERROR: Private key not found: {args.private_key}", file=sys.stderr)
        sys.exit(1)

    inventory = json.load(sys.stdin)

    # Find Windows hosts
    windows_group = inventory.get("tag_OS_Type_windows", {})
    windows_hosts = windows_group.get("hosts", [])

    if not windows_hosts:
        print("No Windows hosts found in inventory.")
        return

    print(f"Retrieving passwords for {len(windows_hosts)} Windows instance(s)...")

    host_vars_dir = args.host_vars_dir
    os.makedirs(host_vars_dir, exist_ok=True)

    success_count = 0
    for host in windows_hosts:
        instance_id = get_instance_id(inventory, host)
        if not instance_id:
            print(f"  WARNING: Could not find EC2 instance ID for host {host}", file=sys.stderr)
            continue

        print(f"  Instance: {instance_id} ({host})")
        password = get_password(instance_id, args.private_key)

        if password:
            # Write host_vars file for this host
            host_vars_file = os.path.join(host_vars_dir, f"{host}.yml")
            with open(host_vars_file, "w") as f:
                f.write("# Auto-generated by get-windows-passwords.py\n")
                f.write(f"# Instance: {instance_id}\n")
                f.write(f"# Generated: {__import__('datetime').datetime.now().isoformat()}\n")
                f.write("---\n")
                f.write(f"ansible_password: '{password}'\n")
            print(f"    ✓ Password written to {host_vars_file}")
            success_count += 1
        else:
            print(f"    ✗ Could not retrieve password (instance may still be initializing)", file=sys.stderr)

    print(f"\nDone. {success_count}/{len(windows_hosts)} passwords retrieved.")
    if success_count == 0 and windows_hosts:
        print("NOTE: Windows instances may need more time to initialize before the password is available.")
        sys.exit(0)  # Don't fail the pipeline, playbook will hit UNREACHABLE


if __name__ == "__main__":
    main()